/** @type {import('stylelint').Config} */

const config = {
    extends: [
        "stylelint-config-standard-scss",
        "stylelint-config-recess-order",
        "stylelint-config-tailwindcss",
        "stylelint-config-sass-guidelines",
        "stylelint-config-prettier-scss",
    ],
    plugins: ["stylelint-order"],
    rules: {
        "scss/operator-no-newline-before": null,
        "scss/operator-no-unspaced": null,
        "at-rule-no-unknown": true,
        "scss/at-extend-no-missing-placeholder": null,
        "scss/dollar-variable-colon-space-after": "always",
        "scss/dollar-variable-colon-space-before": "never",
        "scss/double-slash-comment-empty-line-before": null,
        "selector-pseudo-class-no-unknown": [
            true,
            {
                ignorePseudoClasses: ["global", "has", "is"],
            },
        ],
        "import-notation": "string",
        "no-descending-specificity": null,
        "function-no-unknown": true,
        "no-unknown-animations": true,
        "no-unknown-custom-media": true,
        "unit-no-unknown": true,
        "at-rule-property-required-list": {
            "font-face": ["font-family", "src", "font-display"],
            media: ["prefers-color-scheme", "prefers-reduced-motion"],
            supports: ["display"],
            property: ["property-name", "syntax", "initial-value", "inherits"],
            viewport: ["width", "height"],
            keyframes: ["from", "to"],
            container: ["container-type", "container-name"],
            layer: ["name"],
        },
        "color-hex-alpha": "never",
        "color-named": "never",
        "declaration-property-unit-disallowed-list": {
            "/^margin/": ["px"],
            "/^padding/": ["px"],
            width: ["px"],
            height: ["px"],
            "min-width": ["px"],
            "max-width": ["px"],
            "min-height": ["px"],
            "max-height": ["px"],
            "/^border/": ["px"],
            "/^gap$/": ["px"],
            "/^column-gap$/": ["px"],
            "/^row-gap$/": ["px"],
            "font-size": ["px"],
            "line-height": ["px"],
            "letter-spacing": ["px"],
            "word-spacing": ["px"],
            "text-indent": ["px"],
            "/^(top|right|bottom|left)$/": ["px"],
            "box-shadow": ["px"],
            "text-shadow": ["px"],
            "border-radius": ["px"],
            "/^outline/": ["px"],
            "flex-basis": ["px"],
            "column-width": ["px"],
            "text-decoration-thickness": ["px"],
            "text-underline-offset": ["px"],
            "/^scroll-padding/": ["px"],
            perspective: ["px"],
        },
        "declaration-property-unit-allowed-list": {
            "font-size": ["rem", "em", "%", "vw", "vmin", "vmax"],
            "line-height": ["%", "em", "rem"],
            "letter-spacing": ["em", "rem"],
            "word-spacing": ["em", "rem"],
            "text-indent": ["em", "rem", "%"],
            "/^margin/": ["rem", "em", "%"],
            "/^padding/": ["rem", "em", "%"],
            "/^(column-)?gap$/": ["rem", "em", "%"],
            "row-gap": ["rem", "em", "%"],
            width: ["%", "rem", "em", "vw", "dvw", "ch", "vmin", "vmax"],
            height: ["vh", "dvh", "lvh", "svh", "rem", "em", "%", "vw", "dvw", "vmin", "vmax"],
            "min-width": ["rem", "em", "%", "vw", "dvw", "ch"],
            "max-width": ["rem", "em", "%", "vw", "dvw", "ch", "vmin", "vmax"],
            "min-height": ["vh", "dvh", "lvh", "svh", "rem", "em", "%"],
            "max-height": ["vh", "dvh", "lvh", "svh", "rem", "em", "%", "vw", "dvw"],
            "/^border(-width|-top-width|-right-width|-bottom-width|-left-width)?$/": ["em", "rem"],
            "/^border-radius/": ["em", "rem", "%"],
            "outline-width": ["em", "rem"],
            "outline-offset": ["em", "rem"],
            "/^(top|right|bottom|left)$/": ["%", "rem", "em", "vh", "vw"],
            "box-shadow": ["em", "rem"],
            "text-shadow": ["em", "rem"],
            filter: ["%"],
            "flex-basis": ["%", "rem", "em", "vw", "dvw"],
            "column-width": ["em", "rem", "ch"],
            "/^(transition|animation)-delay$/": ["ms"],
            "/^(transition|animation)-duration$/": ["ms"],
            "text-decoration-thickness": ["em", "rem", "%"],
            "text-underline-offset": ["em", "rem"],
            "/^scroll-padding/": ["rem", "em", "%"],
            perspective: ["rem", "em"],
        },
        "function-url-scheme-disallowed-list": ["http", "https", "/^http/"],
        "function-url-scheme-allowed-list": ["data", "/^file/"],
        "media-feature-name-disallowed-list": ["min-width", "max-width", "min-height", "max-height"],
        "media-feature-name-unit-allowed-list": {
            width: ["rem", "em", "ch"],
            height: ["rem", "em", "ch"],
            "aspect-ratio": [],
            color: [],
            "color-index": [],
            monochrome: [],
            resolution: ["dpi", "dpcm"],
        },
        "media-feature-name-value-allowed-list": {
            orientation: ["portrait", "landscape"],
            scan: ["interlace", "progressive"],
            grid: ["0", "1"],
            update: ["none", "slow", "fast"],
            "overflow-block": ["none", "scroll", "optional-paged", "paged"],
            "overflow-inline": ["none", "scroll"],
            "prefers-color-scheme": ["light", "dark", "no-preference"],
            "prefers-reduced-motion": ["reduce", "no-preference"],
            "prefers-reduced-transparency": ["reduce", "no-preference"],
            "prefers-reduced-data": ["reduce", "no-preference"],
            "prefers-contrast": ["more", "less", "custom", "no-preference"],
            "prefers-forced-colors": ["active", "none"],
            pointer: ["none", "coarse", "fine"],
            hover: ["none", "hover"],
            "any-pointer": ["none", "coarse", "fine"],
            "any-hover": ["none", "hover"],
            "color-gamut": ["srgb", "p3", "rec2020"],
            "display-mode": ["fullscreen", "standalone", "minimal-ui", "browser"],
            "forced-colors": ["none", "active"],
            "inverted-colors": ["none", "inverted"],
            "light-level": ["dim", "normal", "washed"],
            "video-dynamic-range": ["standard", "high"],
            "video-color-gamut": ["srgb", "p3", "rec2020"],
        },
    },
    ignoreFiles: ["node_modules/**", ".next/**", "dist/**", "build/**", "coverage/**"],
};

export default config;
